# Generated by Django 4.2 on 2023-05-23 10:16

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_tweetimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.reply_image_store),
        ),
    ]
